language: erlang
branches:
  only:
    - master
notifications:
  email: arcusfelis@gmail.com
otp_release:
  - 18.3
  - 19.3
  - 20.0
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - unixodbc  # for mssql
      - tdsodbc   # for mssql
